config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'
  root 'countries#index'
  resources :countries do
    post 'load_data', on: :collection
  end
  resources :trips
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.email == 'smart@example.com'
        can :manage, :all
      else
        can :read, :all
      end
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :currency
  has_and_belongs_to_many :trips
  delegate :name, to: :currency, prefix: true

  scope :visited, -> { where(visited: true)}

  def self.import
    Currency.destroy_all
    Country.destroy_all
    currencies = CurrencyAPI.get_currencies
    currencies.each do |currency|
      curr = Currency.find_or_create_by(name: currency['Currency'])
      Country.create( name: currency['Name'],
                      country_code: currency['CountryCode'],
                      currency_code: currency['CurrencyCode'],
                      currency: curr)
    end
  end

  def self.visit!(country_ids)
    where(id: country_ids).update_all(visited: true)
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :countries
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_and_belongs_to_many :countries
  after_save :visit_countries, if: :country_ids_present?

  private

  def visit_countries
    diff = (DateTime.parse(date.to_s) - DateTime.now.at_midnight).to_i
    diff <= 0 ? Country.visit!(country_ids) : TripsWorker.perform_in(diff.days, country_ids)
  end

  def country_ids_present?
    country_ids.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  inherit_resources
  respond_to :js, :html
  load_and_authorize_resource

  def index
    filter = { :currency_id => params[:filter][:currency] } if params[:filter].present? && params[:filter][:currency].present?
    filter = { visited: params[:visited] } if params[:visited].present?
    @countries = filter.present? ? Country.includes(:currency).where(filter) : Country.includes(:currency).all
    @countries.order!(:name)
  end

  def load_data
    Country.import
    redirect_to countries_path
  end

  def trips
    @countries = Country.where(visited: true)
  end

  protected

  def permitted_params
    params.permit(country: [:name, :visited, :country_code, :currency_code, :currency_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :resource
  def new
  end

  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        redirect_back_or url_after_create
      else
        flash.now.notice = status.failure_message
        render 'sessions/new', status: :unauthorized
      end
    end
  end

  def destroy
    sign_out
    redirect_to url_after_destroy
  end

  protected

  def title_prefix
    'Authentication'
  end

  def resource
    @user
  end

  def url_after_create
    # Clearance.configuration.redirect_url
    root_url
  end

  def url_after_destroy
    root_url
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  inherit_resources
  respond_to :js, :html
  load_and_authorize_resource

  protected

  def permitted_params
    params.permit(trip: [:description, :date, :country_ids => []])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/_filter.html.haml
= simple_form_for :filter, url: countries_path, method: :get do |f|
  = f.input :currency, collection: Currency.all
  = f.submit 'Filter', class: 'btn btn-success'
%hr

app/views/countries/_visited_button.html.haml
= link_to visited ? 'Visided' : 'Not Visided', country_path(country_id, country: { visited: !visited }), method: :patch, remote: true, class: "btn btn-#{visited ? 'success' : 'primary'}"

app/views/countries/index.html.haml
.container
  - if @countries.any?
    .col-md-6= render 'filter'
    .col-md-6
      .btn-group.pull-right
        = link_to 'Countries to visit', countries_path(visited: false), class: 'btn btn-primary'
    .clearfix
    .panel.panel-default.panel-primary
      .panel-heading
        %h3.panel-title Countries
      .panel-body
        %table.table.table-bordered
          %thead
            %tr
              %th Name
              %th Country Code
              %th Currency
              %th Currency Code
              %th
          %tbody
            - @countries.each do |country|
              %tr
                %td= country.name
                %td= country.country_code
                %td= country.currency_name
                %td= country.currency_code
                %td{data: { country: { name: country.name } } }
                  - if can? :edit, Country
                    = render 'visited_button', country_id: country.id, visited: country.visited?
                  - else
                    = country.visited? ? 'Visited' : 'Not visited'

  - else
    = link_to 'Load data', load_data_countries_path, method: :post, class: 'btn btn-primary'

app/views/countries/update.js.erb
$("[data-country-name='<%= resource.name %>']").html("<%= escape_javascript render 'visited_button', country_id: resource.id, visited: resource.visited? %>")

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tags

    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"

  %body
    %header
      .container-fluid
        .navbar-header.navbar-header-large
          %ul.nav.navbar-nav.pull-left
            %li= link_to 'Home', root_path
            %li= link_to 'Countries', countries_path
            %li= link_to 'Trips', trips_path
        .navbar-sub-header
        %ul.nav.navbar-nav.pull-right
          %li
            - if user_signed_in?
              = link_to current_user.email, destroy_user_session_path, method: :delete
            - else
              = link_to "Sign in", new_user_session_path
        .clearfix

    %header.navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container-fluid
        %button.navbar-toggle{class: 'pull-left'}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

    %section
      .container-fluid
        = yield

app/views/trips/_form.html.haml
= simple_form_for resource do |f|
  = f.input :description
  = f.input :date
  = f.association :countries, collection: Country.all, multiselect: true
  = f.submit class: 'btn btn-success'

app/views/trips/edit.html.haml
.container
  .page-header
    %h1
      %span Edit Trip
  = render 'form'

app/views/trips/index.html.haml
.container
  .page-header
    %h1
      %span Listing Trips
      - if can? :create, Trip
        = link_to 'New trip', new_trip_path, class: 'btn btn-success'

  .panel.panel-default.panel-primary
    .panel-heading
      %h3.panel-title Trips
    .panel-body
      %table.table.table-bordered
        %thead
          %tr
            %th Description
            %th Date
            %th Countries count
            %th Actions
        %tbody
          - collection.each do |trip|
            %tr
              %td= trip.description
              %td= trip.date.strftime('%D')
              %td= trip.countries.count
              %td
                = link_to 'Show', trip_path(trip), class: 'btn btn-primary'
                - if can? :delete, Trip
                  = link_to 'Remove', trip_path(trip), method: :delete, confirm: 'Are you sure want to delete trip?', class: 'btn btn-danger'

app/views/trips/new.html.haml
.container
  .page-header
    %h1
      %span New Trip
  = render 'form'

app/views/trips/show.html.haml
.container
  .page-header
    %h1
      %span Trip
      - if can? :edit, Trip
        = link_to 'Edit', [:edit, resource], class: 'btn btn-primary'
      - if can? :destroy, Trip
        = link_to 'Remove', resource, method: :delete, data: { confirm: 'Are you sure want to remove this trip?' } , class: 'btn btn-danger'

      .btn-group.pull-right
        = link_to 'Back to trips', trips_path, class: 'btn btn-primary'
  %b Desctiption:
  = resource.description
  %br/
  %b Date:
  = resource.date.strftime('%D')
  %br/
  - if resource.countries.any?
    %b Countries to visit:
    %ul
    - resource.countries.each do |c|
      %li=c.name

app/views/welcome/index.html.haml
.container
  = link_to 'List Available Currencies', currencies_path, class: 'btn btn-primary'
  %hr

  = simple_form_for :currency, url: currencies_path, method: :get do |f|
    = f.input :currency_name
    = f.submit 'Identify the countries by currency name', class: 'btn btn-success'
  %hr

  = link_to 'Countries', countries_path